Bom.Vulnerabilities model
CycloneDX/cyclonedx-javascript-library pull request #163
Opened 2022-08-06 17:55 UTC by thepwagner

Add [Vulnerabilties](https://cyclonedx.org/docs/1.4/json/#vulnerabilities) to the Bom model, including enums as needed.

The implementation is styled after the existing `Component` implementation and tests.

2022-08-07 06:09 UTC, jkowalleck commented
Thank you for this feature.  Review will take me a while. 
Are you planning on implementing the JSON- and XML normalizer, too?

2022-08-07 07:09 UTC, jkowalleck requested changes
partial review. 

please find critical remarks with an :x: .
other remarks are discussion items.

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityRatingSeverity.ts
> +export enum VulnerabiltyRatingSeverity {
:x: please add funcional tests ala https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/tests/functional/Enums.ComponentScope.spec.js

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityRatingMethod.ts
> +export enum VulnerabilityRatingMethod {
:x: please add functional tests ala https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/tests/functional/Enums.ComponentScope.spec.js

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityAnalysisState.ts
> +export enum VulnerabilityAnalysisState {
:x: please add functional tests ala https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/tests/functional/Enums.ComponentScope.spec.js

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityAnalysisResponse.ts
> +export enum VulnerabilityAnalysisResponse {
:x: please add functional tests ala https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/tests/functional/Enums.ComponentScope.spec.js

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityAnalysisJustification.ts
> +export enum VulnerabilityAnalysisJustification {
:x: please add functional tests ala https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/tests/functional/Enums.ComponentScope.spec.js

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityAffectsVersionStatus.ts
> +export enum VulnerabilityAffectsVersionStatus {
:x: please add functional tests ala https://github.com/CycloneDX/cyclonedx-javascript-library/blob/main/tests/functional/Enums.ComponentScope.spec.js

2022-08-07 07:09 UTC, jkowalleck commented on src/enums/vulnerabilityAffectsVersionStatus.ts
> +export enum VulnerabilityAffectsVersionStatus {
rename to `ImpactAnalysisAffectedStatusType` like in XML schema definition? 
rename to `AffectedStatus` like in JSON schema definition?

2022-08-07 07:09 UTC, jkowalleck commented on tests/unit/Models.Vulnerability.spec.js
> +    assert.strictEqual(vulnerability.references.size, 0)
:x: please add type checks -- as a regression test to find unintended type chages (which would lead to breaking changes)

2022-08-07 07:09 UTC, jkowalleck commented on tests/unit/Models.Vulnerability.spec.js
> +  test('constructor with OptionalProperties', () => {
:+1:

2022-08-07 10:51 UTC, thepwagner commented on src/enums/vulnerabilityAnalysisResponse.ts
> +export enum VulnerabilityAnalysisResponse {
I switched to `ImpactAnalysisResponse` as this was the most consistent with the JSON schema, even if the JSON schema doesn't give this enum a standalone definition.

Please advise if you'd prefer a different name.

2022-08-07 12:00 UTC, thepwagner commented on src/models/vulnerability.ts
> +  cwes: number[]
Thanks for this tip! Reusing `PositiveInteger` made this easy. Do you think `CWE[]` is the best type for this collection?


Something like `SortableSet<CWE>` would be great, but I couldn't sort out the TypeScript to have the `CWE` type implement `Comparable`.

2022-08-07 12:55 UTC, thepwagner commented
@jkowalleck thank you for the quick initial feedback!
I've addressed feedback and resolved the threads I think are resolved - please advise if you'd prefer to resolve after verifying the fixes.

* I made all suggested renames, biased towards the naming of the JSON schema.
* I've extended the `compare()` methods to consider all fields, including nested sets like `Set<URL | string>` or `SortableSet<VulnerabilityReference>`. This meant adding a generic `SortableSet.compare()`
* Using the JSON schema for functional tests is cool! I extended the name-mapping helper to support `snake_case` since there was no feedback on the naming of enum values in the first review.

I was not intending to implement the normalizers.

2022-08-08 10:08 UTC, jkowalleck requested changes
please find critical chaneg requests marked with :x: '
everything else is a discussion item.

2022-08-08 10:08 UTC, jkowalleck commented on src/models/vulnerabilityCredits.ts
> +  organizations?: OrganizationalEntityRepository
:x: repositories must not be optiional, but they may be empty

2022-08-08 10:08 UTC, jkowalleck commented on src/models/vulnerabilityCredits.ts
> +  individuals?: OrganizationalContactRepository
:x: repositories must not be optiional, but they may be empty

2022-08-08 10:08 UTC, jkowalleck commented on src/models/vulnerabilityRating.ts
> +    return (this.score ?? 0) - (other.score ?? 0)
this appears to be like an insufficient comparison.
if this is enough to properly compare, then please add a in-code comment that explains why.

2022-08-08 10:08 UTC, jkowalleck commented on src/models/vulnerabilityReference.ts
> +    return (this.id ?? '').localeCompare(other.id ?? '')
:x:  unnecessary null-comparisson

2022-08-08 10:08 UTC, jkowalleck commented on src/models/vulnerabilitySource.ts
> +  url?: URL | string
:x:  use type refenrences ala `VulnerabilitySource['url']`

2022-08-12 14:42 UTC, closed without merging

2022-08-12 14:55 UTC, jkowalleck commented
thank you for all your work, @thepwagner 

could you open a pull request with your latest things and have it target the "feature/vulnerabilities" branch ? 
Plan is to merge your models in there, fine tune them a bit and merge them into master for an early release.

Then, in a later feature, the normalizers and serializers can be developed and be released separately. 

This way you (ad others) will have the models for use soon,
and will not be blocked by normalization details.

2023-01-20 13:36 UTC, jkowalleck commented
work continues in #419