Fix Issue #922 Assert correct URL
CycloneDX/cyclonedx-javascript-library pull request #996
Opened 2023-12-05 08:42 UTC by mLuca

2023-12-05 08:47 UTC, mLuca commented
I am not a Typescript developer, yet I want to have this fix -> I propose a concept for fixing this issue in order to get feedback

2023-12-05 10:49 UTC, jkowalleck requested changes

2023-12-05 10:49 UTC, jkowalleck commented on src/serialize/json/normalize.ts
> +    let encodedUrl: string | undefined
simplify:
```ts
data.url === undefned ? 
  ? undefined
  : encodeURI(data.url.toString())  
```

2023-12-05 11:01 UTC, jkowalleck commented
the proposed solution is insufficient. it will double-encode.
test with an already properly encoded url: 
```js
encodeURI("https://acme.org/foo%5B%5D=bar")
// actual: "https://acme.org/foo%255B%255D=bar"
// expected: "https://acme.org/foo%5B%5D=bar"
```

2023-12-06 15:46 UTC, jkowalleck commented on src/serialize/json/normalize.ts
> +          ? percentEncodeUrl(url)
the encoding should have happened before the `JsonSchema.isIriReference()` is run on it.

2023-12-06 15:46 UTC, jkowalleck commented on src/serialize/json/normalize.ts
> +        url: data.url === undefined
I forgot to add the `JsonSchema.isIriReference()` here.
could you add it?
if it returned false, the the url should be omitted

2023-12-06 15:46 UTC, jkowalleck commented on src/serialize/json/normalize.ts
>      return this._factory.spec.supportsExternalReferenceType(data.type)
the encoding should have happened before the `JsonSchema.isIriReference()` is run on it?
if it returns false, then `normalize` should return `undefined`

2023-12-06 15:46 UTC, jkowalleck commented on src/serialize/xml/normalize.ts
> +          ? makeTextElement(percentEncodeUrl(url), 'url')
`percentEncodeUrl()`  should be applied before `XmlSchema.isAnyURI(url)` is checked

2023-12-06 15:46 UTC, jkowalleck commented on src/serialize/xml/normalize.ts
>    normalize (data: Models.ExternalReference, options: NormalizerOptions, elementName: string): SimpleXml.Element | undefined {
the encoding should have happened before the `XmlSchema.isAnyURI()` is run on it?
if it returns false, then `normalize` should return `undefined`

2023-12-06 15:46 UTC, jkowalleck commented on src/_helpers/percentEncodedUrl.ts
> +const encoderMap = new Map<string, string>([
a frozen dictionary would fit better, here

2023-12-06 15:46 UTC, jkowalleck commented on src/_helpers/percentEncodedUrl.ts
> +const regEx = new RegExp(Object.keys(encoderMap).join('|'), 'gi')
why the `gi` flags? 
please write unit tests for `percentEncodeUrl` and see if the flags are needed,

2023-12-11 09:19 UTC, jkowalleck commented
@mLuca i will add unit tests and fix your implementation.

2023-12-11 12:00 UTC, jkowalleck commented on src/serialize/xml/normalize.ts
>    normalize (data: Models.ExternalReference, options: NormalizerOptions, elementName: string): SimpleXml.Element | undefined {
done via https://github.com/CycloneDX/cyclonedx-javascript-library/pull/996/commits/95fb7c92e28f9bf5ed8f2378ad550f41d2f4d0bf

2023-12-11 12:01 UTC, jkowalleck commented on src/serialize/json/normalize.ts
>      return this._factory.spec.supportsExternalReferenceType(data.type)
done via https://github.com/CycloneDX/cyclonedx-javascript-library/pull/996/commits/95fb7c92e28f9bf5ed8f2378ad550f41d2f4d0bf

2023-12-11 12:02 UTC, jkowalleck commented on src/serialize/json/normalize.ts
> +        url: data.url === undefined
done via https://github.com/CycloneDX/cyclonedx-javascript-library/pull/996/commits/95fb7c92e28f9bf5ed8f2378ad550f41d2f4d0bf

2023-12-11 12:08 UTC, jkowalleck approved these changes

2023-12-11 12:19 UTC, merged